#!/usr/bin/python3

from test import *

def main():
    check_environment()

    run("minikube version")

    test_profile = "skupper-example-high-availability"
    test_kubeconfig = make_temp_file()
    west_kubeconfig = make_temp_file()
    east_kubeconfig = make_temp_file()

    with open("/tmp/minikube-tunnel-output", "w") as tunnel_output_file:
        with working_env(KUBECONFIG=test_kubeconfig):
            try:
                run(f"minikube -p {test_profile} start")
                run(f"minikube -p {test_profile} addons enable ingress")

                copy(test_kubeconfig, east_kubeconfig)
                copy(test_kubeconfig, west_kubeconfig)

                with start(f"minikube tunnel -p {test_profile}", output=tunnel_output_file):
                    run_test(west_kubeconfig, east_kubeconfig)

                notice("Test result: PASSED")
            except:
                error("Test result: FAILED")
                raise
            finally:
                call(f"minikube delete -p {test_profile}")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
